# Docker Compose -> Lê o arquivo e coisa o bagulho diretamnete p nós

services:
  web:
    image: httpd 
    ports: 
      - "8080:80"
    volumes:
      - ./page:/usr/local/apache2/htdocs/

# docker compose up -> no terminal, estando dentro d todas as pastas
